language: python
python:
  - "3.9"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - touch settings.json
  - cat example.settings.json >> settings.json
  - inv test

after_success:
  - coveralls  # upload coverage report to coverals